<#
.SYNOPSIS
    Interactive Cloudflare Tunnel setup generator for LocalPilot Fleet.

.DESCRIPTION
    Generates cloudflare/config.yml and prints step-by-step instructions for
    creating and connecting a Cloudflare Tunnel that exposes your LocalPilot
    Fleet Command Center to managed devices that are roaming off the LAN.

    Optionally installs cloudflared as a persistent Windows Service.

.PARAMETER TunnelName
    The name to give the Cloudflare Tunnel. Defaults to 'localpilot-fleet'.

.PARAMETER LocalPort
    The local port your Fleet server is listening on. Defaults to 8443.

.PARAMETER Hostname
    The public Cloudflare-managed hostname that will front your tunnel,
    e.g. 'fleet.yourdomain.com'. Required for a complete config.

.PARAMETER InstallService
    Switch. If provided, registers cloudflared as a persistent Windows Service
    after generating the config. Requires Administrator privileges.

.EXAMPLE
    .\Generate-TunnelConfig.ps1 -Hostname fleet.example.com
    .\Generate-TunnelConfig.ps1 -TunnelName my-fleet -LocalPort 9443 -Hostname fleet.example.com -InstallService
#>

[CmdletBinding(SupportsShouldProcess)]
param(
    [string]  $TunnelName    = 'localpilot-fleet',
    [int]     $LocalPort     = 8443,
    [string]  $Hostname      = '',
    [switch]  $InstallService
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# Colour helpers
function Write-Banner {
    Write-Host ''
    Write-Host '  +============================================================+' -ForegroundColor Cyan
    Write-Host '  |   LocalPilot Fleet -- Cloudflare Tunnel Generator          |' -ForegroundColor Cyan
    Write-Host '  +============================================================+' -ForegroundColor Cyan
    Write-Host ''
}

function Write-Step {
    param([int]$Number, [string]$Text)
    Write-Host "  [$Number] " -ForegroundColor Cyan -NoNewline
    Write-Host $Text -ForegroundColor White
}

function Write-Code {
    param([string]$Text)
    Write-Host "       $Text" -ForegroundColor Yellow
}

function Write-Ok   { param([string]$T); Write-Host "  [OK]  $T" -ForegroundColor Green  }
function Write-Warn { param([string]$T); Write-Host "  [!!]  $T" -ForegroundColor Yellow }
function Write-Fail { param([string]$T); Write-Host "  [XX]  $T" -ForegroundColor Red    }

# Constants
$CLOUDFLARED = 'C:\Program Files (x86)\cloudflared\cloudflared.exe'
$SCRIPT_DIR  = $PSScriptRoot
$CONFIG_OUT  = Join-Path $SCRIPT_DIR 'config.yml'

# Banner
Write-Banner

# 1. Check cloudflared exists
Write-Host '  Checking prerequisites...' -ForegroundColor Gray

if (-not (Test-Path $CLOUDFLARED)) {
    Write-Fail "cloudflared.exe not found at: $CLOUDFLARED"
    Write-Warn 'Download from: https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/'
    exit 1
}

$cfVersion = & $CLOUDFLARED --version 2>&1 | Select-Object -First 1
Write-Ok "cloudflared found: $cfVersion"

# 2. Resolve current Windows username
$currentUser = $env:USERNAME
if ([string]::IsNullOrWhiteSpace($currentUser)) {
    $currentUser = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name.Split('\')[-1]
}

# 3. Prompt for Hostname if not supplied
if ([string]::IsNullOrWhiteSpace($Hostname)) {
    Write-Host ''
    Write-Host '  Enter the Cloudflare public hostname for your Fleet server.' -ForegroundColor Gray
    Write-Host '  Example: fleet.yourdomain.com' -ForegroundColor DarkGray
    $Hostname = Read-Host '  Hostname'
    if ([string]::IsNullOrWhiteSpace($Hostname)) {
        Write-Warn 'No hostname provided -- using placeholder "fleet.yourdomain.com"'
        $Hostname = 'fleet.yourdomain.com'
    }
}

Write-Ok "Tunnel name : $TunnelName"
Write-Ok "Hostname    : $Hostname"
Write-Ok "Local port  : $LocalPort"
Write-Host ''

# 4. Build tunnel-id placeholders
$TUNNEL_ID_PLACEHOLDER  = '<TUNNEL-ID>'
$CREDS_PATH_PLACEHOLDER = "C:\Users\$currentUser\.cloudflared\<TUNNEL-ID>.json"

# 5. Write config.yml
$genDate = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
$configContent = @"
# LocalPilot Fleet -- Cloudflare Tunnel Configuration
# Generated by Generate-TunnelConfig.ps1 on $genDate
#
# After running 'cloudflared tunnel create $TunnelName', replace
# <TUNNEL-ID> below with the UUID printed by that command.

# The UUID of your named tunnel (from: cloudflared tunnel list)
tunnel: $TUNNEL_ID_PLACEHOLDER

# Path to the tunnel credentials JSON written by cloudflared tunnel create
credentials-file: $CREDS_PATH_PLACEHOLDER

# Ingress rules -- evaluated top-to-bottom; first match wins
ingress:
  # Route all traffic for your public hostname to the local Fleet server
  - hostname: $Hostname
    service: http://localhost:$LocalPort

  # Catch-all: return 404 for any unmatched request (required by cloudflared)
  - service: http_status:404
"@

if ($PSCmdlet.ShouldProcess($CONFIG_OUT, 'Write Cloudflare config.yml')) {
    Set-Content -Path $CONFIG_OUT -Value $configContent -Encoding UTF8
    Write-Ok "Config written to: $CONFIG_OUT"
}

# 6. Print step-by-step setup instructions
Write-Host ''
Write-Host '  ---------------------------------------------------------------' -ForegroundColor DarkGray
Write-Host '  SETUP STEPS -- run these in PowerShell (no elevation needed)' -ForegroundColor White
Write-Host '  ---------------------------------------------------------------' -ForegroundColor DarkGray
Write-Host ''

Write-Step 1 'Log in to Cloudflare (opens browser, one-time per machine):'
Write-Code "& '$CLOUDFLARED' login"
Write-Host ''

Write-Step 2 "Create the named tunnel (copy the UUID it prints):"
Write-Code "& '$CLOUDFLARED' tunnel create $TunnelName"
Write-Host ''

Write-Step 3 'Edit config.yml -- replace <TUNNEL-ID> with the UUID from step 2.'
Write-Code "notepad `"$CONFIG_OUT`""
Write-Host ''

Write-Step 4 "Route your DNS hostname to the tunnel:"
Write-Code "& '$CLOUDFLARED' tunnel route dns $TunnelName $Hostname"
Write-Host ''

Write-Step 5 "Test the tunnel (runs in foreground -- Ctrl+C to stop):"
Write-Code "& '$CLOUDFLARED' tunnel --config `"$CONFIG_OUT`" run $TunnelName"
Write-Host ''

Write-Host '  ---------------------------------------------------------------' -ForegroundColor DarkGray
Write-Host '  Once the tunnel is up, roaming devices enroll with:' -ForegroundColor Gray
Write-Host "    .\agent\Install-LocalPilotNode.ps1 -ServerUrl https://$Hostname -FleetKey <YOUR-KEY>" -ForegroundColor DarkYellow
Write-Host '  ---------------------------------------------------------------' -ForegroundColor DarkGray
Write-Host ''

# 7. Optional: install cloudflared as a Windows Service
if ($InstallService) {
    Write-Host '  -InstallService specified -- launching Install-CloudflaredService.ps1...' -ForegroundColor Cyan
    $installScript = Join-Path $SCRIPT_DIR 'Install-CloudflaredService.ps1'

    if (-not (Test-Path $installScript)) {
        Write-Fail "Install-CloudflaredService.ps1 not found at: $installScript"
        Write-Warn 'Run Install-CloudflaredService.ps1 manually after completing the steps above.'
    } else {
        if ($PSCmdlet.ShouldProcess('cloudflared Windows Service', 'Install and start')) {
            & $installScript -ConfigPath $CONFIG_OUT -TunnelName $TunnelName
        }
    }
}

Write-Host ''
Write-Ok 'Generate-TunnelConfig.ps1 complete.'
Write-Host ''
